package capstoneBackend.ca.sheridancollege.beans;

import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "clothing_items")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ClothingItem {

    @Id
    private String id;

    private String userId;

    /** Base64-encoded product image generated by Imagen */
    private String generatedImageBase64;

    private Tags tags;

    private Date createdAt;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Tags {
        private String type;
        private String color;
        private String style;
        private List<String> occasion;
    }
}
